### ISSUE TITLE
bug: Pick large file

### ISSUE THREAD

**Issue by truonghai1302** [robingenz/capacitor-file-picker#16]
**Plugin version:**

capacitor-file-picker@0.2.0

**Platform(s):**

Android

**Current behavior:**

When I try to pick a large file with a size of 90mb but nothing happened

**Expected behavior:**

Return a result or error to display error message

**Comment by robingenz** [comment]
Thank you for your request. I'm going to take a look at that soon.

**Comment by robingenz** [comment]
Sorry for the late response. I was able to reproduce the issue. I will look for a solution.

**Comment by truonghai1302** [comment]
> Sorry for the late response. I was able to reproduce the issue. I will look for a solution.

No problem, I have cloned your library and temporarily fixed follow my requirement project. Thanks a lot.

**Comment by 3zzy** [comment]
Wondering if there's an ETA cause I'm looking to use this plugin but my files are also going to be large. Thanks

**Comment by robingenz** [comment]
Unfortunately, I could not find a solution so far. If anyone has ideas, feel free to share them.

**Comment by 3zzy** [comment]
@robingenz  There's already a merged PR that appears to fix it: https://github.com/robingenz/capacitor-file-picker/pull/17 ?
The issue most likely is due to the data being passed as base64 string even on web where the blob is already available for use which seems unnecessary.

**Comment by robingenz** [comment]
#17 tried to work around this problem by reading the file only if it is smaller than 15MB. 
This workaround may work on some devices, but it doesn't have to.

There is already a feature request, which should allow you to skip reading the file and get only the metadata (see #12). I will implement that in the next days.

**Comment by maxcodefaster** [comment]
+1 this issue. Our usecase is to read the native file path of a video and then convert the uri with the filesystem api to be played in a video tag. This will not work when converting the file to base64. 

Another thought: Is there a way to choose the gallery as input as well?

**Comment by robingenz** [comment]
#17 has just been published. You can now choose whether file data should be read or not.

```
npm install @robingenz/capacitor-file-picker@0.3.0
```

**Comment by 3zzy** [comment]
@robingenz On the web with `readData: false` shouldn't it pass the blob like the native file input?

**Comment by robingenz** [comment]
> @robingenz On the web with `readData: false` shouldn't it pass the blob like the native file input?

You mean you want to have access to the original File/Blob instance? Best create a new issue so we don't have to discuss it here.

**Comment by truonghai1302** [comment]
Thanks for your update. My problem have been solved by its.
