### ISSUE TITLE
bug: Android preview image is zoomed

### ISSUE THREAD

**Issue by riderx** [robingenz/capacitor-file-picker#21]
**Plugin version:**
`0.2.2`

**Platform(s):**
Android

**Current behaviour:**
show zoomed one

**Expected behaviour:**
should show 100% of the picture

**Steps to reproduce:**
Select a picture in gallery and then the preview is over zoom

**Related code:**

```
const file = async() => {
  try {
    const filePicked = await FilePicker.pickFiles({
      types: ['image/png', 'application/pdf'],
      multiple: false,
    })
    if (!filePicked.files.length) return
    emit('file', {
      ...filePicked.files[0],
    })
  }
  catch (error) {
    console.error(error)
  }
}

```

**Other information:**

https://user-images.githubusercontent.com/4084527/147690473-c2ded188-ba20-47f4-b4d5-ae5cc9ebfac8.mov

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/ios: 3.3.3

Installed Dependencies:

  @capacitor/cli: 3.3.2
  @capacitor/android: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/ios: 3.3.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @riderx, thank your for your request.
I will look into this as soon as possible.
Can you please create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)? I already have the plugin actively in use and have not been able to recreate such an error yet.
Please also attach the image you choose.

**Comment by riderx** [comment]
@robingenz sorry i didn't see the preview was made by someone of my team.
