### ISSUE TITLE
bug: when select only types 'image/jpeg' in android i can pick heic format

### ISSUE THREAD

**Issue by riderx** [robingenz/capacitor-file-picker#22]
**Plugin version:**
Latest

**Platform(s):**
Android

**Current behavior:**
If i select only 'image/jpeg'  i can still pick `heic` types.

**Expected behavior:**
Heic should be not pickable or coverted to right format 

**Steps to reproduce:**
Download heic file here : https://filesamples.com/formats/heic
And try to pick with this code : 
```
    const filePicked = await FilePicker.pickFiles({
      types: ['image/jpeg', 'image/png'],
      multiple: false,
    })
    console.log('filePicked', filePicked)
```
You should be able to pick and see in your logs heic format

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.3.4
  @capacitor/core: 3.3.4
  @capacitor/android: 3.3.4
  @capacitor/ios: 3.3.4

Installed Dependencies:

  @capacitor/cli: 3.3.3
  @capacitor/android: 3.3.3
  @capacitor/core: 3.3.3
  @capacitor/ios: 3.3.3

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @riderx,
Thank you for your request and for filling out the issue template.
I will have a look as soon as possible.

**Comment by robingenz** [comment]
@riderx Unfortunately I could not reproduce the problem (see [this video](https://user-images.githubusercontent.com/13857929/149031218-e55b6dc7-da86-46e6-8fa0-e084f1bc2b8e.mov)). Please create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by riderx** [comment]
It was on Android 10, i'm upgrading to 11 to see if i still have it.

**Comment by robingenz** [comment]
Okay, let me know if this helps.

**Comment by riderx** [comment]
@robingenz yes i confirm it's issue with Android 10. HEIC photo can be selected.
In Android 11 in gallery i cannot select photo, but can select in google Photo ( who probably do the conversion for us )
