### ISSUE TITLE
[FEAT] Pick from gallery / camera roll

### ISSUE THREAD

**Issue by maxcodefaster** [robingenz/capacitor-file-picker#24]
Is it in the scope of the plugin to choose whether to pick from files or from gallery / camera roll ? Thank you very much

**Comment by robingenz** [comment]
Hi @maxcodefaster,
sorry, I forgot to answer you earlier.
This is not in the scope of this plugin. For that I would recommend the official camera plugin. That works very well.
For this reason, I am closing the issue. Please let me know if you have any questions.

**Comment by maxcodefaster** [comment]
Ok thank you for your fast reply. As far as I know the official camera plugin can not pick videos.

**Comment by robingenz** [comment]
Yes, you are right. That is also my state of knowledge.

You can try the following:

```ts 
import { FilePicker } from '@robingenz/capacitor-file-picker';

const pickFiles = async () => {
  const result = await FilePicker.pickFiles({
    types: ['video/mp4', 'video/mpeg'], // And so on... Maybe `video/*` works too.
  });
};
```

This does not open the gallery app, but the file picker. By using the `types` option only videos can be selected.
Does that help you?

**Comment by maxcodefaster** [comment]
Additionaly to the file picker we choose https://github.com/apache/cordova-plugin-camera#module_Camera.PictureSourceType 

Thank you :)

**Comment by raykin** [comment]
@robingenz Just come across this issue when looking for reference about video types restriction.
In my test, 'video/*' can work on PWA/bowser, but can't work on iOS. 'video/*' seems support native in HTML File API.
