### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by tobiasmuecksch** [robingenz/capacitor-file-picker#26]
In the readme the `size` property of the [File type](https://github.com/robingenz/capacitor-file-picker#file) is explained with "The size of the file." But in what unit? It looks like bytes but I'm not sure. A little clarification would be nice.

![Bildschirmfoto 2022-03-26 um 22 33 04](https://user-images.githubusercontent.com/1294854/160257898-a05a93f1-283e-4bd6-84e6-d315991b930e.png)

P.S.: While I'm already commenting the readme. In most of you capacitor projects it's hard to find out for which platforms they are made. It would be nice to have a little table (or something like that) with a short overview of the supported platforms.

**Comment by robingenz** [comment]
Hi @tobiasmuecksch,
yes, the unit is bytes. I have expanded the description (see 8e2c454f6831ca464dbd3042d7b4f27294a5dde4).

> In most of you capacitor projects it's hard to find out for which platforms they are made. It would be nice to have a little table (or something like that) with a short overview of the supported platforms.

All my plugins basically support all official Capacitor platforms (Android, iOS, Web). If a method is not available on a platform, then this is documented in the description of the method.
I follow the format that is also used for the official Capacitor plugins.
I may add a table or something similar to this in the future.

**Comment by tobiasmuecksch** [comment]
Thanks for the clarification!
