### ISSUE TITLE
FilePicker.pickFiles is not in android implemntaion

### ISSUE THREAD

**Issue by Thirumalai08** [robingenz/capacitor-file-picker#27]
Using Capacitor 3 framework with Ionic React. When i try implemnting in android it throws me error
**FilePicker.pickFiles is not in android implementation**. Please help me how to implment in both ios and android

**Comment by robingenz** [comment]
Hi,
You can find the installation instructions in the README.md.
If it does not work, please create a minimal, reproducible example as GitHub repo.
